/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ejemplo_Llamada */

#ifndef _Included_ejemplo_Llamada
#define _Included_ejemplo_Llamada
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ejemplo_Llamada
 * Method:    imprime_saludo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ejemplo_Llamada_imprime_1saludo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
