/* DO NOT EDIT THIS FILE - it is machine generated 
NO TOCAR NADA EN ESTE ARCHIVO*/
#include <jni.h>
/* Header for class ejemplo_Llamada */

#ifndef _Included_ejemplo_Llamada
#define _Included_ejemplo_Llamada
#ifdef __cplusplus
extern "C" {
#endif
/*
<<<<<<< Upstream, based on branch 'master' of https://github.com/Javichincity/websimple
 * Class:     ejemplo_Llamada (La clase de Java sobre la que trabaja)
 * Method:    imprime_saludo (El metodo de la clase de Java)
=======
 * Class:     ejemplo_Llamada
 * Method:    imprime_saludo
>>>>>>> 3573081 JNI finalizado
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ejemplo_Llamada_imprime_1saludo
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
